---
title: "Annexe"
author: "BastienG"
date: "2023-09-08"
output:
  bookdown::pdf_document2:
    extra_dependencies: ["adjustbox", "subfig", "flafter"]
    toc: FALSE
    keep_tex: TRUE
    template: template.tex
    #md_extensions: "-autolink_bare_uris"
    number_sections: TRUE
    citation_package: default # Can also be "natbib"
  bookdown::html_document2:
  bookdown::word_document2: 
    # Produces largely readable output, though some cross-referencing may fail. Useful for collaboration.
    toc: TRUE
---

`r if(!parameter_mapped){cat_title("# Annexe", child_headerinside = child_header)}`

```{r eval=!parameter_mapped}

df_mapping_final_this_dimension <- read_csv("data/mapping_codelist_summary.csv")

df_mapping_final_this_dimension_tidy <- df_mapping_final_this_dimension %>% dplyr::select(-trg_codingsystem)%>%dplyr::group_by(across(everything())) %>%  dplyr::mutate(src_codingsystem = unlist(str_split(src_codingsystem, "_"))[1]) %>% dplyr::ungroup() 

df_mapping_final_this_dimension_tidy_pivoted<-pivot_wider(df_mapping_final_this_dimension_tidy %>% dplyr::mutate(src_code = as.character(src_code)), names_from = source_authority,names_prefix = "Ancient name for ", values_from = "src_code", values_fn = list)  %>% dplyr::rename("New code" = trg_code) %>% dplyr::rename(Dimension = src_codingsystem)%>%
    relocate(Dimension)
mapping <- as_grouped_data(df_mapping_final_this_dimension_tidy_pivoted, groups = c("Dimension")) %>% as.data.frame() %>% dplyr::ungroup()

mapping_final <- mapping %>% rowwise() %>% dplyr::mutate(Dimension = ifelse(is.na(Dimension), " ", Dimension)) %>% dplyr::ungroup() %>% as.data.frame() %>% dplyr::mutate(`New code` = ifelse(is.na(`New code`) &  (Dimension == " "), "UNK", `New code`))
mapping_final[is.na(mapping_final)] <- ""


```

```{r eval=!parameter_mapped}

qflextable2(mapping_final, captionn = "Replacement code during the mapping", folder = "replacement_code_mapping")

```


