-- DROP schemas
DROP SCHEMA "schooltype" CASCADE;
DROP SCHEMA "sex" CASCADE;
DROP SCHEMA "sizeclass" CASCADE;
DROP SCHEMA "metadata" CASCADE;
DROP SCHEMA "species" CASCADE;
DROP SCHEMA "time" CASCADE;
DROP SCHEMA "fact_tables" CASCADE;
DROP SCHEMA "source" CASCADE;
DROP SCHEMA "area" CASCADE;
DROP SCHEMA "catchtype" CASCADE;
DROP SCHEMA "unit" CASCADE;
DROP SCHEMA "flag" CASCADE;
DROP SCHEMA "gear" CASCADE;
