ARG BASE_IMAGE=gta-workflow:geoflow-1.3.0
FROM ${BASE_IMAGE}
USER root
ENV S6_VERSION=v2.1.0.2 RSTUDIO_VERSION=latest DEFAULT_USER=rstudio \
    PANDOC_VERSION=default PATH=/usr/lib/rstudio-server/bin:$PATH
RUN /rocker_scripts/install_rstudio.sh && /rocker_scripts/install_pandoc.sh
ENTRYPOINT []
CMD ["/init"]
EXPOSE 8787
