
```{r child-env-base}

child_env_base <- new.env()
source(knitr::purl("Functions_markdown.Rmd", quiet=TRUE),child_env_base)


```

```{r parameters-global, include=FALSE}


if(!exists("parameter_fact") | is.null("parameter_fact")){parameter_fact <-  "catch"}

parameter_filtering <-list(species = NULL, fishingfleet = NULL)

if(is.character(parameter_filtering)){
  parameter_filtering <- eval(parse(text=toString(parameter_filtering)))
}

parameters_child <- list(config = config, entity = entity,opts = opts ,action = action, parameter_filtering = parameter_filtering, parameter_fact = parameter_fact, parameter_con = con,parameter_host =config$software$input$dbi_config$parameters$host, parameter_port = config$software$input$dbi_config$parameters$port,  parameter_user = config$software$input$dbi_config$parameters$user,parameter_dbname=config$software$input$dbi_config$parameters$dbname, parameter_password = config$software$input$dbi_config$parameters$password,  child = TRUE, no_recap_options = TRUE, plotting_type = "plot",parameter_colnames_to_keep = c("fishing_fleet",         "gear_type",                 "time_start",                 
                      "geographic_identifier","fishing_mode",           "species",                       
                      "measurement_unit",                 "measurement_value",                "source_authority"), treatment = FALSE, shapefile.fix = shapefile.fix, shape_without_geom = shape_without_geom, continent = continent,species_group = species_group, cl_cwp_gear_level2 = cl_cwp_gear_level2, fig.path = fig.path, outputonly = FALSE)

list2env(parameters_child, env = child_env_base)

```

