---
title: 'Comparison of two data sets'
date: "`r format(Sys.time(), '%d %B, %Y')`"
author:
  - name: Bastien Grasset
    email: bastien.grasset@ird.fr
    affiliation:
      - IRD
      - MARBEC
  - name: Julien Barde
    affiliation:
      - IRD
      - MARBEC
address:
  - code: IRD
    address: Institut de Recherche pour le Développement (IRD), av. Jean Monnet, CS 30171, 34203 Sète cédex, France
  - code: MARBEC
    address: MARBEC, University of Montpellier, CNRS, Ifremer, IRD, Sète, France
# bibliography: ["IOTC-2022-WPDCS18.bib"] # Replace with one or more of your own bibtex files. Better BibTeX for Zotero is your friend
csl: dmk-format.csl # Use any CSL style. See https://www.zotero.org/styles for a good list. Ignored if citation_package: natbib
link-citations: TRUE
output:
  bookdown::pdf_document2:
    extra_dependencies: ["adjustbox", "subfig", "flafter"]
    toc: TRUE
    keep_tex: TRUE
    template: template.tex
    #md_extensions: "-autolink_bare_uris"
    number_sections: TRUE
    citation_package: default # Can also be "natbib"
  bookdown::html_document2:
  bookdown::word_document2: 
    # Produces largely readable output, though some cross-referencing may fail. Useful for collaboration.
    toc: TRUE
lang: en # Main document language in BCP47 format
geometry: "margin=25mm"
papersize: a4
#linestretch: 2 # for double spacing
endfloat: FALSE # Set to TRUE to turn on latex endfloat package to place figures and tables at end of document
# endfloatoption: # See endfloat documentation for more possibilities
#   - tablesfirst # Default
#   - nomarkers # Default
numberlines: FALSE
authblk: FALSE # FALSE = author affiliations in footnotes; TRUE = author affiliations in a block below author names
footnotehyper: FALSE # TRUE will give you enhanced table footnote capabilities. Set to FALSE to be able to use French blocks. Needed due to what appears to be a latex bug.
urlcolor: blue
linkcolor: blue
citecolor: blue
graphics: TRUE # Needed to be able to include images
tables: TRUE # Needed to be able to include tables
fancyhdr:
  first:
    headleft: "`r ifelse(exists('headleft_title'), headleft_title, 'Comparaison')`"
    headright: "`r ifelse(exists('headleft_title'), headleft_title, 'Comparaison')`"
    headrulewidth: 0pt
    #footleft: A left foot
    footrulewidth: 0pt
  subsequent:
    headleft: "`r ifelse(exists('headleft_title'), headleft_title, 'Comparaison')`"
    headright: "`r ifelse(exists('headleft_title'), headleft_title, 'Comparaison')`"
    headrulewidth: 1pt
    footrulewidth: 0pt
---


```{r setuprmd}

res <- knitr::knit_child("Setup_markdown.Rmd", quiet = TRUE, envir = environment())

```

```{r sourcingfunctionsmarkdown}

source("https://raw.githubusercontent.com/firms-gta/geoflow-tunaatlas/Developement/Analysis_markdown/functions/Functions_markdown.R", local = TRUE)

```


```{r parameter-settings}

source("https://raw.githubusercontent.com/firms-gta/geoflow-tunaatlas/Developement/Analysis_markdown/functions/Parameters_settings.R", local = TRUE)

```

`r if(step_title_t_f){cat_title(step_title, child_headerinside = child_header)}`

```{r fileformatting, results='asis'}

source("https://raw.githubusercontent.com/firms-gta/geoflow-tunaatlas/Developement/Analysis_markdown/functions/file_formatting.R", local = TRUE)

```


```{r Groupping-datarmd, results='asis'}

source("https://raw.githubusercontent.com/firms-gta/geoflow-tunaatlas/Developement/Analysis_markdown/functions/Groupping_differences.R", local = TRUE)

```

```{r checkifnodiff,  eval=!unique_analyse , results='asis'}

if (round(sum_valeur_init) == round(sum_valeur_final) & nrow(Groupped_all %>%dplyr::filter(`Loss / Gain` != 'Egal'))==0){
  cat("There are no differences between the two datasets, this step is not changing the data in any way")}

```


```{r explenation, results='asis'}

res <- knitr::knit_child("Explenation.Rmd", quiet = TRUE, envir = environment())

cat(res)

```

`r if(!unique_analyse && parameter_short == FALSE ){cat_title("# Main differences \n ", child_headerinside = child_header)}`


```{r SummarydifferencesRmd, eval=!unique_analyse, results='asis'}

res <- knitr::knit_child("Summarydifferences.Rmd", quiet = TRUE, envir = environment())

cat(res, sep =  "\\clearpage")

```

```{r Compnumberstratas, eval=!unique_analyse, echo=FALSE, results='asis'}

res <- knitr::knit_child("Compnumberstratas.Rmd", quiet = TRUE, envir = environment())

cat(res, sep =  "\\clearpage")

```

```{r parametershort,  eval=parameter_short, results='asis'}

exit <- "This document only presents the summary of the differences between the two datasets. If you need a more detailed summary please provide FALSE as argument for the 'short' parameter"

if(child){exit <- ""}

if (parameter_short){knitr::knit_exit(exit, fully = FALSE)}


```

```{r Main-caracteristics-of-dataset, results='asis', eval=!unique_analyse}

res <- knitr::knit_child("Main_differences.Rmd", quiet = TRUE, envir = environment())

cat(res, sep =  "\\clearpage")

```

```{r Main-caracteristics-of-dataset, results='asis', eval = coverage}

res <- knitr::knit_child("Main_caracteristics_of_dataset.Rmd", quiet = TRUE, envir = environment())

cat(res, sep =  "\\clearpage")

```

\clearpage


```{r recapwithout-mappingg, Diff-for-other-dimensions,eval = (!unique_analyse & !parameter_mapped), results='asis'}

res <- knitr::knit_child("Recap_without_mapping.Rmd", quiet = TRUE, envir = environment())

cat(res, sep =  "\\clearpage")

```


\clearpage

```{r annexe, eval = FALSE, results='asis'}

res <- knitr::knit_child("Annexe.Rmd", quiet = TRUE, envir = environment())

cat(res, sep =  "\\clearpage")

```

\clearpage

