---
title: "Everyotherdimension"
author: "BastienG"
date: "2023-09-12"
output:
  bookdown::pdf_document2:
    extra_dependencies: ["adjustbox", "subfig", "flafter"]
    toc: FALSE
    keep_tex: TRUE
    template: template.tex
    number_sections: TRUE
    citation_package: default
  bookdown::html_document2:
  bookdown::word_document2: 
    toc: TRUE
---

# Repartition of the data for the other dimensions

We check the distribution of the value of each dimension and each unit.

```{r pie-charts-multiple, eval =!unique_analyse}

  pie_chart_knit <- mapply(FUN = knitting_plots_subfigures, plot = other_dimension_analysis_list$figures, title = other_dimension_analysis_list$dimension_title_subfigures, MoreArgs = list(folder = "Piechartdimensions", fig.pathinside = fig.path))
  bar_chart_knit <- mapply(FUN = knitting_plots_subfigures, plot = other_dimension_analysis_list$barplots, title = other_dimension_analysis_list$dimension_title_subfigures, MoreArgs = list(folder = "Barplot", fig.pathinside = fig.path))
  
```


```{r otherdimensionanalysis, echo=FALSE, results='asis', eval =!unique_analyse}

cat(unlist(pie_chart_knit), sep = "\n")

```


```{r subfigures, eval=unique_analyse}

render_subfigures(plots_list = other_dimension_analysis_list$figures, titles_list = other_dimension_analysis_list$dimension_title_subfigures, general_title = "Other dimensions")

```

```{r subfigures, eval=unique_analyse}

render_subfigures(plots_list = barplots, titles_list = dimension_title_subfigures, general_title = "Other dimensions")

```


```{r otherdimensionanalysisbarplots, echo=FALSE, results='asis', eval=FALSE}
cat(unlist(bar_chart_knit), sep = "\n")
```




