---
title: "Filtering_data"
author: "BastienG"
date: "2023-09-12"
ouput: html_document
---


```{r filterprinting, echo=FALSE, results='asis'}

if (isNullList(parameter_filtering)){cat("There is no filter on this data")} else {
  
  cat (paste0("The filter used on this data are:  \n "))
  for (i in 1:length(parameter_filtering)){
    if (parameter_filtering[i] %in% parameter_filtering & !is.null(parameter_filtering[[i]])){
      cat(paste0("***- On ", names((parameter_filtering)[i]), " : ", paste((parameter_filtering)[[i]], collapse = " ; "),"*** \n"))
    } else {""}
  }
}



```



```{r filteringfunctiononsetup}

formals(filtering_function, envir = environment())$parameter_filtering = parameter_filtering


```

```{r filterprinting, echo=FALSE}

if (!is.null(parameter_resolution_filter)) {

      filtering_resolution_filter <- function(datatable, first_digit) {
        filtered_data <- datatable[substr(datatable$geographic_identifier, 1, 1) == first_digit, ]
        return(filtered_data)
      }
    
      init <- filtering_resolution_filter(init, opts$resolution_filter)
      
      final <- filtering_resolution_filter(final, opts$resolution_filter)
    }

```


```{r filteringfunctionondata}

init <- filtering_function(dataframe_to_filter = init)

if(unique_analyse){final <- init[0,]} else {final <- filtering_function(final)}

```