---
title: "geographic_difftest"
author: "BastienG"
date: "2023-09-08"
output: html_document
---



```{r eval=FALSE}

fonction_empreinte_spatiale_diff  = function(measurement_unit, plotting_type, shapefile_fix_function, t_filtered, percent = FALSE){
  if (deparse(substitute(measurement_unit)) == "X[[i]]"){ #for sapply function bug
  assign("new_name", paste0("Difference in millions of ",measurement_unit), envir = globalenv())
    if(percent){assign("new_name", paste0("Difference (in %) of ", measurement_unit), envir = globalenv())}
    }else {  assign("new_name", paste0("Difference in millions of ", substitute(measurement_unit)), envir = globalenv())
    if(percent){assign("new_name", paste0("Difference (in %) of ", substitute(measurement_unit)), envir = globalenv())}
    }
  
  enquo_unit <- enquo(measurement_unit)
  dataset <- dplyr::inner_join(shapefile_fix_function,(t_filtered%>% dplyr::ungroup() %>%dplyr::filter(Dimension == ("geographic_identifier")) %>% dplyr::filter(measurement_unit == !!enquo_unit)) , by = c("CWP_CODE"= "Precision"))
  if(percent){
  dataset <- dataset%>%  dplyr::rename(!!as.symbol(eval(parse(text = "new_name"))) := "Difference (in %)")} else {
  dataset <- dataset%>%  dplyr::rename(!!as.symbol(eval(parse(text = "new_name"))) := "Difference in value")}
image_child <- tm_shape(dataset) +tm_fill(eval(parse(text = "new_name")), palette= ("-PiYG"), id= ("name"), midpoint = 0)+tm_facets(by =   c("GRIDTYPE", "Loss / Gain"),free.coords = FALSE)+tm_borders(lwd = 0.05)
  if(plotting_type == "plot"){image_child <-image_child+tm_shape(continent)+tm_borders()}
  return(list(image_child,measurement_unit))
}

tmap_mode(plotting_type)
formals(tm_shape)$drop.empty_facets <- FALSE
formals(fonction_empreinte_spatiale_diff)$plotting_type <- plotting_type
formals(fonction_empreinte_spatiale_diff)$shapefile_fix_function <- shapefile.fix
formals(fonction_empreinte_spatiale_diff)$t_filtered <- t_filtered
# t_filtered <- t

map_diff <- lapply(unique(t_filtered$measurement_unit), fonction_empreinte_spatiale_diff)
map_diff


map_plotted_knit <- lapply(map_diff, knit_child_map)
formals(fonction_empreinte_spatiale_diff)$percent <- TRUE
map_diff_percent <- lapply(unique(t_filtered$measurement_unit), fonction_empreinte_spatiale_diff)

map_plotted_percent <- lapply(map_diff_percent, knit_child_map)

```


```{r eval=FALSE}
inner_join <- dplyr::inner_join(shapefile.fix,(t %>%dplyr::filter(Dimension == "geographic_identifier")) , by = c("CWP_CODE"="Precision"))%>%dplyr::mutate(`Impact on the data` = as.factor(dplyr::case_when(`Difference (in %)` == 0 ~ 'No differences', `Difference (in %)` == 100~'All data different',`Difference (in %)` < 0 ~ "Gain", TRUE ~ 'Loss')))
t_filtered <- t #%>% dplyr::filter(`Difference (in %)` >= -100)
```




```{r eval=FALSE}

if (nrow(inner_join %>%dplyr::filter(`Impact on the data` == 'All data different'))!=0 & nrow(inner_join %>%dplyr::filter(`Impact on the data` == 'No differences'))!=0){
   try(restest <- lapply(unique(t_filtered$measurement_unit), FUN = knit_child_map))
}

formals(knit_child_map)$percent <- TRUE

if (nrow(inner_join %>%dplyr::filter(`Impact on the data` == 'All data different'))!=0 & nrow(inner_join %>%dplyr::filter(`Impact on the data` == 'No differences'))!=0){
   try(restest_percent <- lapply(unique(t_filtered$measurement_unit), FUN = knit_child_map))
}
```


```{r eval=FALSE,echo=FALSE, results='asis'}


try(cat(unlist(map_plotted_knit), sep = "\\clearpage"))


```

```{r eval=FALSE, echo=FALSE, results='asis'}


try(cat(unlist(map_plotted_percent), sep = "\\clearpage"))


```




```{r geographicaldiffplotting, eval = FALSE, echo=FALSE,  results='asis'}

save_image(paste0("Geographical differences in % between ", titre_1, " and ", titre_2),image,  folder = "Geografdiff")

```
