---
title: "Grouppingdifferences"
author: "BastienG"
date: "2023-09-12"
output: html_document
---

```{r groupping-differences, message=FALSE, warning=FALSE, include=FALSE}

units <- unique(c(unique(init$measurement_unit), unique(final$measurement_unit)))

Dimensions <- colnames(init)[colnames(init) != "measurement_unit" & colnames(init)!= "measurement_value"& colnames(init)!= "SURFACE" & colnames(init) %notin% parameter_time_dimension]

carte_init <- fonction_groupement(Dimensions[[1]],init %>% head(1), final%>% head(1))

Groupped_all <- carte_init[0,]

for (i in Dimensions){
  temporaire <- fonction_groupement(i,init, final)
  assign(paste0("Groupped", i), temporaire)
  
  Groupped_all <- rbind(Groupped_all, temporaire)
}

Groupped_all$Dimension <-as.character(Groupped_all$Dimension)
Groupped_all$Precision <-as.character(Groupped_all$Precision)

```

```{r time-dimension-groupping, message=FALSE, warning=FALSE, include=FALSE}

for (i in parameter_time_dimension){
  temporaire <- fonction_groupement(i,init, final)
  assign(paste0("Groupped", i), temporaire)
  
  Groupped_time_dimension <- rbind(Groupped_all, temporaire)
}

```



```{r stratasloss, eval=!unique_analyse, message=FALSE, warning=FALSE, include=FALSE}

nb_ligne_init_millions <- nrow(init)
nb_ligne_final_millions<- nrow(final)
# 
sum_valeur_init <- sum(init$measurement_value, na.rm = TRUE)
sum_valeur_final <- sum(final$measurement_value, na.rm = TRUE)

strates_perdues <- Groupped_all %>%dplyr::filter(value_sum_2 == 0 & `Loss / Gain` == "Loss")
strates_gagnees <- Groupped_all %>%dplyr::filter(value_sum_1 == 0 & `Loss / Gain` == "Gain")
nombre_strates_perdues <- nrow(strates_perdues)
nombre_strates_gagnees <- nrow(strates_gagnees)
nombres_de_strates_totales <- nrow(Groupped_all)
pourcentage_strates_perdues <- 100-(100*((nombres_de_strates_totales-nombre_strates_perdues)/nombres_de_strates_totales))
gc()

strates_perdues_first_10 <- rbind(strates_perdues,strates_gagnees) %>%dplyr::filter(`Loss / Gain` != 'Egal')%>%ungroup %>%dplyr::filter(Dimension!="geographic_identifier") %>%dplyr::group_by(`Loss / Gain`,Dimension,measurement_unit)%>%# slice(1:10) %>%
  dplyr::select(Dimension, everything())

if (nrow(strates_perdues_first_10)== 0){strates_perdues_first_10 <- rbind(strates_perdues,strates_gagnees) %>%dplyr::filter(`Loss / Gain` != 'Egal')%>%ungroup %>%dplyr::filter(Dimension!="geographic_identifier") %>%dplyr::group_by(`Loss / Gain`,Dimension,measurement_unit)%>% #slice(1:10) %>%
  dplyr::select(Dimension, everything()) }

strates_perdues_first_10[strates_perdues_first_10==""] <- "NA"
strates_perdues_first_10[is.na(strates_perdues_first_10)] <- "NA"

```


```{r compnumberstratas, eval=!unique_analyse}

number_init_column <- as.data.frame(t(init %>% dplyr::select(-measurement_value) %>% summarise_all(list(~n_distinct(.))))) %>%  dplyr::rename(!!as.symbol(eval(parse(text = "titre_1"))) := V1)
number_final_column <- as.data.frame(t(final %>% dplyr::select(-measurement_value) %>% summarise_all(list(~n_distinct(.)))))%>%  dplyr::rename(!!as.symbol(eval(parse(text = "titre_2"))) := V1)

number_final_column<-number_final_column[order(row.names(number_final_column)), ,drop=F]
number_init_column<-number_init_column[order(row.names(number_init_column)), ,drop=F]


number_init_column_final_column <- cbind(number_init_column , number_final_column ) %>% mutate_all(as.numeric)
number_init_column_final_column$Difference <- number_init_column_final_column[,2]-number_init_column_final_column[,1]

rownames(number_init_column_final_column) <- paste0("Number of ", rownames(number_init_column_final_column))

number_init_column_final_column <- as.data.frame(number_init_column_final_column %>% tibble::rownames_to_column(" "))

```




```{r summaryofdifferences, eval=!unique_analyse}

init_group <- init %>% dplyr::group_by(measurement_unit) %>% dplyr::summarise(titre_test1 = sum(measurement_value)) 

final_group <- final %>% dplyr::group_by(measurement_unit) %>% dplyr::summarise(titre_test2 = sum(measurement_value)) 

summary_of_differences <- dplyr::full_join(init_group, final_group) %>% mutate(across(where(is.numeric), ~replace(., is.na(.), 0))) %>% dplyr::arrange(measurement_unit) %>%dplyr::rowwise() %>%  dplyr::mutate(measurement_unit = paste0(measurement_unit)) %>% dplyr::mutate(Difference = -titre_test1 + titre_test2)%>%mutate("Difference (in %)" = 100*(Difference /titre_test1)) %>%  dplyr::rename(!!as.symbol(eval(parse(text = "titre_1"))) := titre_test1)%>% dplyr::rename(!!as.symbol(eval(parse(text = "titre_2"))) := titre_test2)

```



```{r fonction-grouppement-for-time-dimension, include=FALSE}

time_dimension_list_groupped <- lapply(parameter_time_dimension, fonction_groupement, init = init, final = final)

```


```{r timeanalysisplotcreation}


time_dimension_list_groupped_diff <- lapply(time_dimension_list_groupped, function(x){x %>%dplyr::mutate(Time = as.Date(Precision))%>%  dplyr::rename(`Values dataset 1` = "value_sum_1",`Values dataset 2` = "value_sum_2")%>% pivot_longer(cols = c(`Values dataset 1`, `Values dataset 2`), names_to = "Dataset", values_to ="Values") %>%dplyr::mutate(Dataset = dplyr::case_when(Dataset == "Values dataset 1" ~ titre_1 , TRUE ~ titre_2)) %>% dplyr::distinct()})

if(unique_analyse){
  time_dimension_list_groupped_diff <- lapply(time_dimension_list_groupped_diff, function(x){x %>% filter(Values!=0)})
}

time_dimension_list_groupped_diff_image <- lapply(time_dimension_list_groupped_diff, function(x){ggplot(x) +
aes(
x = Time,
y = Values,
fill = Dataset,
colour = Dataset,
group = Dataset
) +
geom_line(size = 0.5) +
scale_fill_hue(direction = 1) +
scale_color_hue(direction = 1) +
theme_bw() +
theme(legend.position = "top") +
facet_wrap(vars(measurement_unit), nrow = 2L)+
labs(x = unique(x$Dimension), y = "Values")+
facet_grid("measurement_unit", scales = "free_y")})

```


```{r topn}

topn <- 6

```

```{r otherdimension-list-pie-chart}

list_pie_chart <- list(intersect(setdiff(parameter_colnames_to_keep, unlist(list(parameter_time_dimension, parameter_geographical_dimension, "measurement_unit", "measurement_value"))), colnames(init)))[[1]]

```


```{r Groupped-not-disap-or-ap-stratas}

Groupped_all_not_disap_or_app <- Groupped_all  %>% dplyr::filter(`Difference (in %)` %notin% c(0,100, -Inf) & (value_sum_1!=0 )& value_sum_2!=0 ) 

Groupped_all_not_disap_or_app <- Groupped_all_not_disap_or_app %>% filter( Dimension %in% list_pie_chart)


if(nrow(Groupped_all_not_disap_or_app) != 0){
  
    Groupped_all_not_disap_or_app <- Groupped_all_not_disap_or_app %>% dplyr::mutate(`Loss / Gain` = base::ifelse(loss >= 0, "Loss", "Gain")) %>%
    dplyr::mutate(`Loss / Gain` = dplyr::case_when(is.na(`Loss / Gain`) ~ "Gain", value_sum_1 == value_sum_2 ~"Egal", TRUE ~ `Loss / Gain`))%>%
    dplyr::mutate(Dimension = as.factor(Dimension)) %>%  dplyr::group_by(Dimension, measurement_unit,`Loss / Gain`) %>% 
    arrange(desc(abs(.data[[parameter_diff_value_or_percent]]))) %>%
    dplyr::mutate(id = row_number()) %>%  
    dplyr::mutate(Precision = as.factor(base::ifelse(id>(topn),paste0("Others"),paste0(as.character(Precision))))) %>%
    dplyr::ungroup() %>%dplyr::group_by(`Loss / Gain`,Dimension,Precision, measurement_unit) %>%
    dplyr::summarise(across(is.numeric, sum)) %>%
    dplyr::mutate(`Difference (in %)` = (`Difference in value`/value_sum_1)*100) %>%
    dplyr::select(-id, -number_lines2)%>%
    dplyr::group_by(`Loss / Gain`,Dimension,measurement_unit) %>%  arrange(Dimension,measurement_unit,desc(abs(.data[[parameter_diff_value_or_percent]]))) %>%
    mutate(Other_column = ifelse(Precision == "Others", 1, 0)) 



Groupped_all_not_disap_or_app_to_dysplay <- Groupped_all_not_disap_or_app %>% dplyr::ungroup() %>% 
                      dplyr::rename(`Values dataset 1` = "value_sum_1",
                                    `Values dataset 2` = "value_sum_2") %>% 
                      dplyr::filter(`Loss / Gain` != "Egal") %>% 
                      dplyr::select(parameter_columns_to_keep, Other_column) %>% 
                      dplyr::mutate(across(c("Values dataset 1", "Values dataset 2", "Difference in value"),  ~ round(., digits = 0))) %>% 
                       dplyr::mutate_if(is.numeric, base::round, digits=2) %>% 
                      dplyr::group_by(Dimension, measurement_unit, `Loss / Gain`) %>% 
dplyr::arrange(Dimension, measurement_unit, `Loss / Gain`, Other_column, desc(abs(.data[[parameter_diff_value_or_percent]]))) %>%                      dplyr::select(-Other_column)

} else {no_diff_text <- "There are no differences between stratas aside the appearing and disappearing ones"}


```



```{r fonction-empreinte-spatial, eval=print_map}


map_unit <- lapply(units, FUN = fonction_empreinte_spatiale,  initial_dataset = init, final_dataset = final, titre_1 = titre_1, titre_2 = titre_2)


titles <- paste0("Distribution in value for the unit : ",units)


```

```{r numbergridtype, results='asis', eval=print_map}

if(exists("GrouppedGRIDTYPE")){
number_of_GRIDTYPE <- length(unique(GrouppedGRIDTYPE$Precision))
GRIDTYPE <- paste(as.list(unique(GrouppedGRIDTYPE$Precision)), collapse = " ; ")
}

```
