---
title: "Recap_without_mapping"
author: "BastienG"
date: "2023-09-08"
output:
  bookdown::pdf_document2:
    extra_dependencies: ["adjustbox", "subfig", "flafter"]
    toc: FALSE
    keep_tex: TRUE
    template: template.tex
    #md_extensions: "-autolink_bare_uris"
    number_sections: TRUE
    citation_package: default # Can also be "natbib"
  bookdown::html_document2:
  bookdown::word_document2: 
    # Produces largely readable output, though some cross-referencing may fail. Useful for collaboration.
    toc: TRUE
---

```{r numberstrataswithtoutmapping}

initnotmapped <- readRDS(paste0(as.character(parameter_init),"/rds.rds"))
finalnotmapped <- readRDS(paste0(as.character(parameter_final),"/rds.rds"))

initnotmapped <- initnotmapped %>% dplyr::select(any_of(parameter_colnames_to_keep))
finalnotmapped <- finalnotmapped %>% dplyr::select(any_of(parameter_colnames_to_keep))


number_init_column <- as.data.frame(t(initnotmapped %>% dplyr::select(-measurement_value) %>% summarise_all(list(~n_distinct(.))))) %>%  dplyr::rename(!!as.symbol(eval(parse(text = "titre_1"))) := V1)
number_final_column <- as.data.frame(t(finalnotmapped %>% dplyr::select(-measurement_value) %>% summarise_all(list(~n_distinct(.)))))%>%  dplyr::rename(!!as.symbol(eval(parse(text = "titre_2"))) := V1)

rm(initnotmapped)
rm(finalnotmapped)

not_mapped_diff <- cbind(number_init_column , number_final_column ) %>% mutate_all(as.numeric)
not_mapped_diff$Difference <- not_mapped_diff[,2]-not_mapped_diff[,1]

rownames(not_mapped_diff) <- paste0("Number of ", rownames(not_mapped_diff))

```

```{r notmappeddiffprinting}

qflextable2(not_mapped_diff %>% tibble::rownames_to_column(" "), captionn = "Comparison of number of stratas between the two datasets with including the differences due to the mapping of codelist", save_folder = "Summary")
```

