---
title: "Timecoverage"
author: "BastienG"
date: "2023-09-12"
---

`r cat_title("## Time coverage", child_headerinside = child_header)`


```{r titles-time-cov}

if(unique_analyse){
  
titles_time <-   paste0("Evolutions of values for the dimension ", parameter_time_dimension, " for ", titre_1, " dataset ")

}else {
  
titles_time <-   paste0("Evolutions of values for the dimension ", parameter_time_dimension, " for ", titre_1, " and ",titre_2, " dataset ")}


```



```{r timeanalysisplotcreation}
## ----timeanalysisplotcreation---------------------------------


time_dimension_list_groupped_diff <- lapply(time_dimension_list_groupped, function(x){x %>%dplyr::mutate(Time = as.Date(Precision))%>%  dplyr::rename(`Values dataset 1` = "value_sum_1",`Values dataset 2` = "value_sum_2")%>% pivot_longer(cols = c(`Values dataset 1`, `Values dataset 2`), names_to = "Dataset", values_to ="Values") %>%dplyr::mutate(Dataset = dplyr::case_when(Dataset == "Values dataset 1" ~ titre_1 , TRUE ~ titre_2)) %>% dplyr::distinct()})

if(unique_analyse){
  time_dimension_list_groupped_diff <- lapply(time_dimension_list_groupped_diff, function(x){x %>% filter(Values!=0)})
}

time_dimension_list_groupped_diff_image <- lapply(time_dimension_list_groupped_diff, function(x){ggplot(x) +
aes(
x = Time,
y = Values,
fill = Dataset,
colour = Dataset,
group = Dataset
) +
geom_line(size = 0.5) +
scale_fill_hue(direction = 1) +
scale_color_hue(direction = 1) +
theme_bw() +
theme(legend.position = "top") +
facet_wrap(vars(measurement_unit), nrow = 2L)+
labs(x = unique(x$Dimension), y = "Values")+
facet_grid("measurement_unit", scales = "free_y")})

```



```{r temporalcoveragelistplot, echo=FALSE, results='asis'} 

time_dimension_list_groupped_diff_image_knit <- mapply(FUN = knitting_plots_subfigures,
                         plot = time_dimension_list_groupped_diff_image,
                         title = titles_time,
                         MoreArgs = list(folder = "Temporal", fig.pathinside = fig.path))

```

```{r temporalcoveragelistplotknitting, echo=FALSE, results='asis'}

cat(unlist(time_dimension_list_groupped_diff_image_knit, recursive = FALSE),  sep = "\n")

```






