---
title: "Recap on pre-harmonisation"
author: "BastienG"
date: "2023-10-18"
output:
  bookdown::html_document2:
    number_sections: true
    toc: true
---



```{r include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	error = 0,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	tab.cap.pre = "Table ",
	tab.cap.sep = ": ", results = 'asis'
)
base::options(knitr.duplicate.label = "allow")
```


```{r options, include=FALSE}

base::options(scipen=9999)
plotting_type <- "plot" 
if (knitr::is_html_output()){plotting_type <- "view" }
tmap_mode(plotting_type)

```


```{r message=FALSE, warning=FALSE, include=FALSE}

set_flextable_defaults(
  font.size = 10,
  font.color = "black",
  digits = 2,
  theme_fun = "theme_box"
)


#set the dataset caption styling
knitr::opts_chunk$set(tab.cap.pre = "Table ", tab.cap.sep = ": ")

#set the dataset caption styling
autonum <- officer::run_autonum(seq_id = "tab", bkm = "TC1", bkm_all = TRUE) # number the table, bkm (bookmark) is important as the cross-referencing is done using the bookmark


```



```{r}

invalid_data <- readr::read_csv(file.path(path, "grouped_results_invalid_data.csv")) %>%ungroup() %>% arrange(tRFMO)%>%  distinct()

columns_to_color <- names(invalid_data)[-c(1,2)]


invalid_data <- invalid_data %>% ungroup() %>%dplyr::rowwise() %>% dplyr::mutate(All_good = ifelse(sum(across(columns_to_color)) ==0, TRUE, FALSE)) %>% arrange(All_good, tRFMO) %>% group_by(All_good, tRFMO)

issued_dataframes <- invalid_data%>% dplyr::filter(All_good == FALSE) %>% dplyr::select(-All_good)

column_names = colnames(issued_dataframes)

# Remove '.csv' from each column name
cleaned_column_names <- gsub(".csv", "", column_names)

colnames(issued_dataframes) <- cleaned_column_names
columns_to_color <- names(issued_dataframes)[-c(1,2)]


```

```{r echo=FALSE, results='asis'}

source("https://raw.githubusercontent.com/firms-gta/geoflow-tunaatlas/master/Analysis_markdown/functions/Functions_markdown.R")
issued_dataframes <- qflextable2(issued_dataframes , captionn = "Recap of the issues with each dataframe", grouped_data = c( "tRFMO"))
for (i in columns_to_color){
  issued_dataframes$body$styles$text$color$data[,i] <- ifelse(is.na(issued_dataframes$body$dataset[,i]), "blue", ifelse(issued_dataframes$body$dataset[,i], "red", "green"))
  
}



```


```{r echo=FALSE, results='asis'}

issued_dataframes

```

```{r}

no_issued_dataframes <- qflextable2(invalid_data %>% dplyr::filter(All_good == TRUE) %>% dplyr::select(c(tRFMO,Entity)), captionn = "Dataframes without known issues", grouped_data = c( "tRFMO"))


```


```{r echo=FALSE, results='asis'}

no_issued_dataframes

```





```{r all-not-mapped}

recap_mapping <- readr::read_csv(file.path(path,"all_not_mapped_data.csv")) %>%ungroup() %>% arrange(source_authority) %>% distinct() %>% arrange(Dimension)

```


```{r echo=FALSE, results='asis'}

qflextable2(recap_mapping, captionn = "All the code not being mapped during the pre-harmonisation", grouped_data = c("source_authority", "Dimension"))

```



```{r all-recap-mapping}

recap_mapping <- readr::read_csv(file.path(path,"all_recap_mapping.csv")) %>%ungroup() %>% arrange(source_authority)%>% dplyr::select(-Entity)  %>% filter(src_code != trg_code) %>% distinct()

```


```{r echo=FALSE, results='asis'}

qflextable2(recap_mapping, captionn = "All the code being mapped during the pre-harmonisation (not displayed if identical)", grouped_data = c("source_authority", "src_codingsystem"))

```
