---
title: "`r paste0('Report on raw data for dataset: ', ifelse(exists('dataset', envir = environment()), dataset, 'NULL'))`"
author: "BastienG"
date: "2023-10-12"
output: html_document
---



```{r include=FALSE}

knitr::opts_chunk$set(
	echo = FALSE,
	error = 0,
	fig.align = "center",
	message = FALSE,
	warning = FALSE,
	tab.cap.pre = "Table ",
	tab.cap.sep = ": ", results = 'asis'
)
base::options(knitr.duplicate.label = "allow")
```


```{r options, include=FALSE}

base::options(scipen=9999)
plotting_type <- "plot" 
if (knitr::is_html_output()){plotting_type <- "view" }
tmap_mode(plotting_type)

```


```{r message=FALSE, warning=FALSE, include=FALSE}

set_flextable_defaults(
  font.size = 10,
  font.color = "black",
  digits = 2,
  theme_fun = "theme_box"
)


#set the dataset caption styling
knitr::opts_chunk$set(tab.cap.pre = "Table ", tab.cap.sep = ": ")

#set the dataset caption styling
autonum <- officer::run_autonum(seq_id = "tab", bkm = "TC1", bkm_all = TRUE) # number the table, bkm (bookmark) is important as the cross-referencing is done using the bookmark


```



```{r sourcingfunctionsmarkdown}

source("https://raw.githubusercontent.com/firms-gta/geoflow-tunaatlas/master/Analysis_markdown/functions/Functions_markdown.R")


```

```{r first}

directory <-ifelse(exists("parameter_directory",envir = environment()), parameter_directory, "~/Documents/geoflow-tunaatlas/jobs/20231013172118/entities/catch_1deg_1m_bb_iattc_level0__tuna_byflag/")

fig.path = directory

```

```{r statsirregularareas}

if(file.exists(file.path(directory, "/data/stats_irregular_areas.rds"))){stats_irregular_areas <- readRDS(file.path(directory, "/data/stats_irregular_areas.rds"))
}

```

```{r not_mapped_total}

if(file.exists(file.path(directory, "/data/not_mapped_total.rds"))){not_mapped_total <- readRDS(file.path(directory, "/data/not_mapped_total.rds"))} 

```


```{r results = 'asis', eval=file.exists(file.path(directory, "/data/outside_juridiction.rds"))}

cat("# Outside juridiction area\n

The data displayed by tRFMOs is supposed to concern the spatial area of the juridiction of the tRFMO. However, some data is displayed outside.")

child_env$parameter_init<- file.path(directory, "/data/outside_juridiction.rds")

res <- knitr::knit_child("comparison.Rmd", envir = child_env, quiet = TRUE)

child_env$parameter_init <- NULL
child_env$parameter_titre_1 <- NULL
        
        
```

```{r complastfirstcat, eval=file.exists(file.path(directory, "/data/outside_juridiction.rds")), echo=FALSE, results='asis'}

cat(res, sep =  "\\clearpage")

```


```{r results = 'asis', eval=file.exists(file.path(directory, "/data/areas_in_land.rds"))}

cat("# Overview of data located on land\n

Only the squares where the integrity of the area is located on land are considered in the analysis.")

child_env$parameter_init<- file.path(directory, "/data/areas_in_land.rds")

child_env$parameter_titre_1  <- "On_continent"
res <- knitr::knit_child("comparison.Rmd", envir = child_env, quiet = TRUE)
        
child_env$parameter_init <- NULL
child_env$parameter_titre_1 <- NULL

        
        
```

```{r statsirregularareasflextable,echo=FALSE, results = 'asis', eval=file.exists(file.path(directory, "/data/stats_irregular_areas.rds"))}

qflextable2(stats_irregular_areas, captionn ="Summary of the irregular area reallocation by unit", pgwidth = 6,  save_folder = "Summary")

```

```{r complastfirstcat, eval=file.exists(file.path(directory, "/data/areas_in_land.rds")), echo=FALSE, results='asis'}

cat(res, sep =  "\\clearpage")

```


```{r results = 'asis', eval=file.exists(file.path(directory, "/data/removed_irregular_areas.rds"))}

cat("# Area not in cwp grid\n

Some square does not correspond to the cwp grid standards")

child_env$parameter_init<- file.path(directory, "/data/removed_irregular_areas.rds")

child_env$parameter_titre_dataset_1  <- "Not_cwp"
res <- knitr::knit_child("comparison.Rmd", envir = child_env, quiet = TRUE)
        
        
child_env$parameter_init <- NULL
child_env$parameter_titre_1 <- NULL

        
```

```{r complastfirstcat, eval=file.exists(file.path(directory, "/data/removed_irregular_areas.rds")), echo=FALSE, results='asis'}

cat(res, sep =  "\\clearpage")

```


```{r results = 'asis', eval=file.exists(file.path(directory, "/data/not_conform_conversion_factors.rds"))}

cat("# Not conform conversion factors\n

Some data provided in Number of fish and tons are not plausible")

child_env$parameter_init<- file.path(directory,  "not_conform_conversion_factors.rds")
child_env$parameter_titre_1  <- "Not_conform_conversions_factors"

res <- knitr::knit_child("comparison.Rmd", envir = child_env, quiet = TRUE)

child_env$parameter_init <- NULL
child_env$parameter_titre_1 <- NULL
       
        
        
```

```{r complastfirstcat, eval=file.exists(file.path(directory, "/data/not_conform_conversion_factors.rds")), echo=FALSE, results='asis'}

cat(res, sep =  "\\clearpage")

```

```{r results = 'asis', eval=file.exists(file.path(directory, "/data/negative_values.rds"))}

cat("# Negative or null values in provided data\n

Some data are provided with a measurement_value inferior or equal to 0 ")

child_env$parameter_init<- file.path(directory,  "negative_values.rds")
child_env$parameter_titre_1  <- "Negative_or_null_values"

res <- knitr::knit_child("comparison.Rmd", envir = child_env, quiet = TRUE)

child_env$parameter_init <- NULL
child_env$parameter_titre_1 <- NULL
        
        
        
```

```{r complastfirstcat, eval=file.exists(file.path(directory, "/data/negative_values.rds")), echo=FALSE, results='asis'}

cat(res, sep =  "\\clearpage")

```



```{r results = 'asis', eval=file.exists(file.path(directory, "/data/not_mapped_total.rds"))}

cat("# Not mapped data \n

Some data provided does not correspond to any mapping")

# child_env$parameter_init<- file.path(directory, "/data/not_mapped_total.rds")
# child_env$parameter_titre_1  <- "not_mapped"
# 
#       res <- knitr::knit_child("comparison.Rmd", envir = child_env, quiet = TRUE)
#         
#         
#         
        
```

<!-- ```{r complastfirstcat, eval=file.exists(file.path(directory, "/data/not_mapped_total.rds")), echo=FALSE, results='asis'} -->

<!-- cat(res, sep =  "\\clearpage") -->

<!-- ``` -->

```{r summaryofthenotmappedfactors,echo=FALSE, results = 'asis', eval=file.exists(file.path(directory, "/data/not_mapped_total.rds"))}

qflextable2(not_mapped_total, captionn ="Summary of the not mapped factors and so replaced by 'UNK', '99.9', or 'NEI'", pgwidth = 6,  save_folder = "Summary", fig.path = getwd())

```




