name: GHCR Rights Smoke Test

on:
  workflow_dispatch: {}   

permissions:
  contents: read
  packages: write         

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GHCR_TOKEN || github.token }}

      - name: Push tiny image (busybox → ghcr.io/<org>/<repo>:ping)
        run: |
          set -e
          IMAGE=ghcr.io/${{ github.repository }}
          docker buildx build --progress=plain \
            --file - \
            -t $IMAGE:ping \
            --push \
            <<'EOF'
          FROM busybox
          CMD ["echo","ping"]
          EOF
